// app/blog/page.tsx
import Link from 'next/link';
import { formatDate, getBlogPosts } from '../lib/posts';

export const metadata = {
	title: 'Blog',
	description: 'Field notes.',
};

export default async function BlogPage() {
	const posts = await getBlogPosts();

	return (
		<section>
			<h1 className='mt-0'>Blog</h1>

			<div className='not-typeset my-6 md:my-8'>
				{posts.map((post) => (
					<Link
						key={post.slug.join('/')}
						href={`/blog/${post.slug.join('/')}`}
						className='flex flex-col space-y-1 mb-4'
					>
						<div className='flex flex-col md:flex-row md:items-baseline md:gap-4'>
							<p className='text-neutral-600 dark:text-neutral-400 text-sm font-mono'>
								{formatDate(post.metadata.publishedAt)} · {post.readingTime} min
								read
							</p>
							<p className='text-neutral-900 dark:text-neutral-100 tracking-tight'>
								{post.metadata.title}
							</p>
						</div>
					</Link>
				))}
			</div>
		</section>
	);
}

// src/routes/blog/+page.svelte
<script lang="ts">
	import { formatDate } from '$lib/utils';
	import BlurFade from '$lib/components/magic/BlurFade.svelte';

	export let data;
	let BLUR_FADE_DELAY = 0.04;
</script>

<svelte:head>
	<title>Blog</title>
</svelte:head>

<BlurFade delay={BLUR_FADE_DELAY}>
	<h1 class="mb-8 text-2xl font-medium tracking-tighter">Blog</h1>
</BlurFade>
<!-- Posts -->
<section>
	<ul class="posts">
		{#each data.posts as post, id (id)}
			<li class="post">
				<BlurFade delay={BLUR_FADE_DELAY * 2 + id * 0.05}>
					<a class="mb-4 flex flex-col space-y-1" href="/blog/{post.slug}">
						<div class="flex w-full flex-col">
							<p class="tracking-tight">{post.title}</p>
							<p class="text-muted-foreground h-6 text-xs">
								{formatDate(post.date)}
							</p>
						</div>
					</a>
				</BlurFade>
			</li>
		{/each}
	</ul>
</section>

<style>
	.posts {
		display: grid;
	}

	.post {
		max-inline-size: var(--size-content-3);
	}

	.post:not(:last-child) {
		border-bottom: 1px solid var(--border);
		padding-bottom: var(--size-7);
	}
</style>
